
name: a11y test

on:
  pull_request:
    branches: [ next ]

jobs:
  Test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: update apt
      run: sudo apt update -y
    - name: Install wget
      run: sudo apt install wget
    - name: Download chrome installation file
      run: wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_90.0.4430.72-1_amd64.deb
    - name: Install required packages
      run: sudo apt-get install -y fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxkbcommon0 libxrandr2 libxshmfence1 xdg-utils
    - name: Install Chrome
      run: sudo dpkg -i google-chrome-stable_90.0.4430.72-1_amd64.deb
    - name: Install dependencies for chromedriver
      run: sudo apt-get install -y libxss1 libappindicator1 libindicator7 xvfb unzip
    - name: Download chromedriver and make it executable
      run: wget https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
    - name: unzip
      run: unzip chromedriver_linux64.zip
    - name: Move executable and create symlinks
      run: sudo mv -f chromedriver ~/
    - name: make executable
      run: chmod +x ~/chromedriver  
    - name: Add directory to path
      run: echo 'export PATH="$HOME:$PATH"' >> ~/.profile
    - name: Add chromedriver to path
      run: echo 'export PATH="/usr/bin:$PATH"' >> ~/.profile
    - name: Reload profile
      run: source ~/.profile
    - name: Check browser version
      run: google-chrome --version
    - name: Check chrome driver
      run: which chromedriver
    - name: install dependencies
      run: npm i
    - name: run Linter
      run: npm run code-sanity
    - name: build components
      run: npm run build:components
    - name: install conduct-a11y-audit
      run: npm i -g conduct-a11y-audit
    - name: run a11y test
      run: a11y-audit -u http://localhost:3333 -s true --ss local
